### ISSUE TITLE
Biotope CLI TypeError when starting new project

### ISSUE THREAD

**Issue by eritislami** [biotope/biotope-cli#127]
**Describe the bug**
When trying to start a new project using the biotope cli (npm install biotope -g) fails with a TypeError. This error occurs with both stable and beta versions that you can select when generating.

**To Reproduce**
1. Install biotope globally with npm
2. Run biotope create my-project

**Expected behavior**
CLI should finish without errors

**Screenshots**
![](https://i.imgur.com/uilKJbP.png)

**Desktop (please complete the following information):**
- MacBook Pro 2019 with Touchbar
- Big Sur 11.5.2
- Node.js v16.6.1
- Npm v7.20.3

**Context**
```
biotope create biotope-project
? Which version do you want to generate? Stable
? Which template do you want to generate? Empty biotope instance
/usr/local/lib/node_modules/biotope/lib/actions/create.js:10
const logError = message => console.log(chalk_1.default.red(message));
                                                        ^

TypeError: Cannot read property 'red' of undefined
    at logError (/usr/local/lib/node_modules/biotope/lib/actions/create.js:10:57)
    at /usr/local/lib/node_modules/biotope/lib/actions/create.js:82:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.create (/usr/local/lib/node_modules/biotope/lib/actions/create.js:81:5)
```

**Comment by eritislami** [comment]
Apologies if this isn't the appropriate repository

**Comment by eritislami** [comment]
After updating node-gyp globally to latest version the cli doesn't error out at the beginning but still does not succesfully complete, on either node 14 & 16 it fails to build with different errors depending on the node version

I have Xcode installed with macOS SDK 11 and command line tools for clang, clang++, make also latest python 3.9

![](https://i.imgur.com/1zS4Pl4.png)
